name: Generate Snake Game from GitHub Contribution Grid

on:
  push:
    branches:
      - main  # Modify this to your default branch

jobs:
  generate_snake_game:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Generate Snake Game
        uses: Platane/snk@v2.2.1

      # Add the code below to integrate your existing code
      - name: Add snake code
        run: |
          const expiresIn = 1000; // 1 hour in milliseconds

          store.subscribe(() => {
            const { auth } = store.getState();
            const expirationTime = new Date().getTime() + expiresIn;
            localStorage.setItem("auth", JSON.stringify(auth));
            localStorage.setItem("time", expirationTime);
          });

          function checkTime() {
            const storedTime = parseInt(localStorage.getItem("time"));

            if (!storedTime || isNaN(storedTime)) {
              return false;
            }

            const currentTime = new Date().getTime();

            if (currentTime > storedTime) {
              localStorage.removeItem("auth");
              return false;
            }

            return true;
          }

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add snake game code
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
